columns = [
    ("Id", "شناسه"),
    ("MSSubClass", "زیررده مسکونی"),
    ("MSZoning", "منطقه‌بندی"),
    ("LotFrontage", "عرض زمین"),
    ("LotArea", "مساحت زمین"),
    ("Street", "نوع خیابان"),
    ("Alley", "کوچه"),
    ("LotShape", "شکل زمین"),
    ("LandContour", "توپوگرافی زمین"),
    ("Utilities", "امکانات عمومی"),
    ("LotConfig", "چیدمان زمین"),
    ("LandSlope", "شیب زمین"),
    ("Neighborhood", "محله"),
    ("Condition1", "شرایط محیطی اول"),
    ("Condition2", "شرایط محیطی دوم"),
    ("BldgType", "نوع ساختمان"),
    ("HouseStyle", "سبک خانه"),
    ("OverallQual", "کیفیت کلی"),
    ("OverallCond", "وضعیت کلی"),
    ("YearBuilt", "سال ساخت"),
    ("YearRemodAdd", "سال بازسازی"),
    ("RoofStyle", "سبک سقف"),
    ("RoofMatl", "جنس سقف"),
    ("Exterior1st", "نمای خارجی اول"),
    ("Exterior2nd", "نمای خارجی دوم"),
    ("MasVnrType", "نوع نمای سنگی"),
    ("MasVnrArea", "مساحت نمای سنگی"),
    ("ExterQual", "کیفیت نمای بیرونی"),
    ("ExterCond", "وضعیت نمای بیرونی"),
    ("Foundation", "نوع پی"),
    ("BsmtQual", "کیفیت زیرزمین"),
    ("BsmtCond", "وضعیت زیرزمین"),
    ("BsmtExposure", "میزان نورگیری زیرزمین"),
    ("BsmtFinType1", "نوع تکمیل زیرزمین ۱"),
    ("BsmtFinSF1", "مساحت تکمیل‌شده زیرزمین ۱"),
    ("BsmtFinType2", "نوع تکمیل زیرزمین ۲"),
    ("BsmtFinSF2", "مساحت تکمیل‌شده زیرزمین ۲"),
    ("BsmtUnfSF", "مساحت زیرزمین ناتمام"),
    ("TotalBsmtSF", "مساحت کل زیرزمین"),
    ("Heating", "سیستم گرمایش"),
    ("HeatingQC", "کیفیت گرمایش"),
    ("CentralAir", "تهویه مرکزی"),
    ("Electrical", "سیستم برق"),
    ("1stFlrSF", "مساحت طبقه اول"),
    ("2ndFlrSF", "مساحت طبقه دوم"),
    ("LowQualFinSF", "مساحت با کیفیت پایین"),
    ("GrLivArea", "مساحت فضای قابل سکونت"),
    ("BsmtFullBath", "حمام کامل زیرزمین"),
    ("BsmtHalfBath", "نیم‌حمام زیرزمین"),
    ("FullBath", "حمام کامل"),
    ("HalfBath", "نیم‌حمام"),
    ("BedroomAbvGr", "تعداد اتاق خواب"),
    ("KitchenAbvGr", "تعداد آشپزخانه"),
    ("KitchenQual", "کیفیت آشپزخانه"),
    ("TotRmsAbvGrd", "تعداد کل اتاق‌ها"),
    ("Functional", "کاربری ساختمان"),
    ("Fireplaces", "تعداد شومینه"),
    ("FireplaceQu", "کیفیت شومینه"),
    ("GarageType", "نوع گاراژ"),
    ("GarageYrBlt", "سال ساخت گاراژ"),
    ("GarageFinish", "وضعیت تکمیل گاراژ"),
    ("GarageCars", "ظرفیت خودرو گاراژ"),
    ("GarageArea", "مساحت گاراژ"),
    ("GarageQual", "کیفیت گاراژ"),
    ("GarageCond", "وضعیت گاراژ"),
    ("PavedDrive", "مسیر آسفالت‌شده"),
    ("WoodDeckSF", "مساحت تراس چوبی"),
    ("OpenPorchSF", "مساحت ایوان باز"),
    ("EnclosedPorch", "ایوان بسته"),
    ("3SsnPorch", "ایوان سه‌فصل"),
    ("ScreenPorch", "ایوان توری‌دار"),
    ("PoolArea", "مساحت استخر"),
    ("PoolQC", "کیفیت استخر"),
    ("Fence", "حصار"),
    ("MiscFeature", "ویژگی متفرقه"),
    ("MiscVal", "ارزش ویژگی متفرقه"),
    ("MoSold", "ماه فروش"),
    ("YrSold", "سال فروش"),
    ("SaleType", "نوع فروش"),
    ("SaleCondition", "شرایط فروش"),
    ("SalePrice", "قیمت فروش")
]
print(columns)